name: "Review Code"
description: "Runs an AI-powered code review using Claude Code with Bitwarden plugins"
inputs:
  azure_subscription_id:
    description: "Azure Subscription ID for OIDC authentication"
    required: true
  azure_tenant_id:
    description: "Azure Tenant ID for OIDC authentication"
    required: true
  azure_client_id:
    description: "Azure Client ID for OIDC authentication"
    required: true
  pr_number:
    description: "Pull request number to review"
    required: true
  repository:
    description: "Repository in owner/repo format"
    required: true
  checkout_ref:
    description: "Git ref to checkout (typically the PR head SHA)"
    required: true
  github_token:
    description: "GitHub token for API access"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        ref: ${{ inputs.checkout_ref }}
        persist-credentials: true

    - name: Log in to Azure
      uses: bitwarden/gh-actions/azure-login@main
      with:
        subscription_id: ${{ inputs.azure_subscription_id }}
        tenant_id: ${{ inputs.azure_tenant_id }}
        client_id: ${{ inputs.azure_client_id }}

    - name: Get Azure Key Vault secrets
      id: get-kv-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: gh-org-bitwarden
        secrets: "ANTHROPIC-CODE-REVIEW-API-KEY"

    - name: Log out from Azure
      uses: bitwarden/gh-actions/azure-logout@main

    - name: Retrieve existing PR threads
      id: retrieve-pull-request-threads
      uses: bitwarden/gh-actions/get-pull-request-threads@main
      with:
        token: ${{ inputs.github_token }}
        pr_number: ${{ inputs.pr_number }}
        repository: ${{ inputs.repository }}

    - name: Review with Claude Code
      uses: anthropics/claude-code-action@f669191d7d1e67f08a54b0c11cf5683a9a391951 # v1.0.49
      with:
        anthropic_api_key: ${{ steps.get-kv-secrets.outputs.ANTHROPIC-CODE-REVIEW-API-KEY }}
        plugin_marketplaces: "https://github.com/bitwarden/ai-plugins.git"
        plugins: |
          bitwarden-code-review@bitwarden-marketplace
          bitwarden-software-engineer@bitwarden-marketplace
          bitwarden-security-engineer@bitwarden-marketplace
        prompt: |
          REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}
            The repository is already checked out at the PR head SHA with full git history (fetch-depth: 0).
            You can read files directly and use git commands to inspect changes.

          /bitwarden-code-review:code-review
        claude_args: |
          --verbose
          --model opus
          --allowedTools "Task,Skill,Read,Grep,Glob,Bash(git diff:*),Bash(git log:*),Bash(git show:*),Bash(gh pr checks:*),Bash(gh pr view:*),Bash(gh pr diff:*),Bash(gh pr review:--comment*),Bash(gh pr comment:*),mcp__github_comment__update_claude_comment,mcp__github_inline_comment__create_inline_comment"
