name: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  tag:
    description: "The name of the branch or tag."
    required: true
  environment:
    description: "The name of the environment."
    required: true
  slack-channel:
    description: "The name of the slack channel."
    required: true
    default: team-eng-qa-devops
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure."
    required: true

runs:
  using: "composite"
  steps:
    - name: Login to Azure - Prod Subscription
      uses: Azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2 # v1.4.7
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}

    - name: Retrieve slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@master
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Post to a Slack channel on start
      if: ${{ inputs.event == 'start' }}
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ":loading: Updating ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n ${{ inputs.url }}."
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}

    - name: Post to a Slack channel on success
      if: ${{ inputs.event == 'success' }}
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ":white_check_mark: Updated ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n ${{ inputs.url }}."
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}

    - name: Post to a Slack channel on failure
      if: ${{ inputs.event == 'failure' }}
      uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ":x: Failed to update ${{ inputs.environment }} to `${{ inputs.tag }}` on ${{ inputs.project }}.\n ${{ inputs.url }}.\nPlease retry or contact @devops team."
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}