name: "Report deployment status to Slack"
description: "Report deployment status to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  project_owner:
    description: "The owner/org of the project"
    required: false
    default: bitwarden
  tag:
    description: "The name of the branch or tag."
    required: true
  commit-sha:
    description: "The SHA of the branch or tag."
    required: true
  db_migration_detected:
    description: "Whether a database migration was detected."
    required: false
    default: false
  environment:
    description: "The name of the environment."
    required: true
  event:
    description: "Deployment event type. Possible values are start, success, or failure."
    required: true
  url:
    description: "URL of the deployment action run"
    required: false
    default: ${{ github.event.deployment_status.target_url }}
  slack-webhook-url:
    description: "Slack incoming webhook URL to post the message to."
    required: true

runs:
  using: "composite"
  steps:
    - name: Slack message setup
      id: setup
      shell: bash
      env:
        INPUT_EVENT: ${{ inputs.event }}
        INPUT_ENVIRONMENT: ${{ inputs.environment }}
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_PROJECT: ${{ inputs.project }}
        INPUT_PROJECT_OWNER: ${{ inputs.project_owner }}
        INPUT_URL: ${{ inputs.url }}
        INPUT_COMMIT_SHA: ${{ inputs.commit-sha }}
        INPUT_DB_MIGRATION_DETECTED: ${{ inputs.db_migration_detected }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        function slack_message_fn () {
          local event="$INPUT_EVENT"
          local environment="$INPUT_ENVIRONMENT"
          local tag="$INPUT_TAG"
          local project="$INPUT_PROJECT"
          local project_owner="$INPUT_PROJECT_OWNER"
          local url="$INPUT_URL"
          local commit_sha="$INPUT_COMMIT_SHA"

          # This action can be called from other repositories with external refs/shas, so use the passed in project rather than github.repository
          local repository_url="$GITHUB_SERVER_URL/$project_owner/$project"

          local commit_url="$repository_url/commit/$commit_sha"
          local tag_url="$repository_url/tree/$tag"

          # Slack link format: https://api.slack.com/reference/surfaces/formatting
          local commit_link="<$commit_url|$commit_sha>"
          local tag_link="<$tag_url|$tag>"

          case $event in
            start)
              SLACK_MESSAGE=":loading: Deploying $tag_link to $environment on $project.\n
              $url\n
              SHA: $commit_link"
              ;;

            success)
              SLACK_MESSAGE=":white_check_mark: Deployed $tag_link to $environment on $project.\n
              $url\n
              SHA: $commit_link"
              ;;

            failure)
              SLACK_MESSAGE=":x: Failed to deploy $tag_link to $environment on $project.\n
              $url\n
              SHA: $commit_link\n
              Please retry. If the issue persists, share this message in the #team-eng-bre channel for support."
              ;;

            cancelled)
              SLACK_MESSAGE=":hand: Cancelled deploy of $tag_link to $environment on $project.\n
              $url\n
              SHA: $commit_link"
              ;;

            no-changes)
              SLACK_MESSAGE=":heavy_minus_sign: No changes were made for $tag_link deployment to $environment on $project.\n
              $url\n
              SHA: $commit_link"
              ;;
          esac
        }

        if [[ "$INPUT_DB_MIGRATION_DETECTED" == true && "$INPUT_TAG" != main && "$INPUT_TAG" != rc && "$INPUT_TAG" != hotfix-rc ]]; then
          slack_message_fn
          SLACK_MESSAGE="$SLACK_MESSAGE\n
          :red_siren: This branch has new database migration changes."
        else
          slack_message_fn
        fi

        echo 'slack_message<<EOF' >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Post message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
      with:
        webhook: ${{ inputs.slack-webhook-url }}
        webhook-type: incoming-webhook
        payload: |
          text: "${{ steps.setup.outputs.slack_message }}"
