---

extends: default

rules:
  braces:
    level: warning
  brackets:
    level: warning
  colons:
    level: warning
  commas:
    level: warning
  comments:
    min-spaces-from-content: 1
  document-start: 
    level: error
    present: false
  document-end:
    level: error
    present: false
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    spaces: 2
  key-duplicates:
    level: warning
  line-length:
    level: warning
    max: 120
  new-line-at-end-of-file:
    level: warning
  new-lines:
    level: warning
  trailing-spaces:
    level: warning
  truthy:
    check-keys: false
    level: warning
