name: "Report release version to Slack"
description: "Report upcoming release version to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  version:
    description: "The upcoming version to release."
    required: true
  slack-channel:
    description: "The name of the Slack channel."
    default: release
  AZURE_SUBSCRIPTION_ID:
    description: "Azure Subscription ID for the service principal."
    required: true
  AZURE_TENANT_ID:
    description: "Azure Tenant ID for the service principal."
    required: true
  AZURE_CLIENT_ID:
    description: "Azure Client ID for the service principal."
    required: true
outputs:
  channel_id:
    description: "Channel ID where the Slack message was posted."
    value: ${{ steps.slack-message.outputs.channel_id }}

runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: bitwarden/gh-actions/azure-login@main
      with:
        subscription_id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        tenant_id: ${{ inputs.AZURE_TENANT_ID }}
        client_id: ${{ inputs.AZURE_CLIENT_ID }}

    - name: Retrieve Slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Azure Logout
      uses: bitwarden/gh-actions/azure-logout@main

    - name: Slack message setup
      id: setup
      shell: bash
      run: |
        function slack_message_fn () {
          local version="${{ inputs.version }}"
          local project="${{ inputs.project }}"
          SLACK_MESSAGE=":meow_attention: Upcoming release \`$version\` for \`$project\`."
        }

        slack_message_fn

        echo "slack_message<<EOF" >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@b0fa283ad8fea605de13dc3f449259339835fc52 # v2.1.0
      with:
        method: chat.postMessage
        token: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
        payload: |
          channel: ${{ inputs.slack-channel }}
          text: "${{ steps.setup.outputs.slack_message }}"
