name: "Report release version to Slack"
description: "Report upcoming release version to Slack"
inputs:
  project:
    description: "The name of the project."
    required: true
  version:
    description: "The upcoming version to release."
    required: true
  slack-channel:
    description: "The name of the Slack channel."
    default: release
  AZURE_KV_CI_SERVICE_PRINCIPAL:
    description: "The service principal used to authenticate to Azure. (Deprecated, use AZURE ID inputs instead)"
    required: false
    default: ""
  AZURE_SUBSCRIPTION_ID:
    description: "Azure Subscription ID for the service principal."
    required: false
    default: ""
  AZURE_TENANT_ID:
    description: "Azure Tenant ID for the service principal."
    required: false
    default: ""
  AZURE_CLIENT_ID:
    description: "Azure Client ID for the service principal."
    required: false
    default: ""
outputs:
  channel_id:
    description: "Channel ID where the Slack message was posted."
    value: ${{ steps.slack-message.outputs.channel_id }}

runs:
  using: "composite"
  steps:
    - name: Missing inputs check
      if: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL == '' && inputs.AZURE_CLIENT_ID == '' }}
      shell: bash
      run: |
        echo "Error: Either AZURE_KV_CI_SERVICE_PRINCIPAL or AZURE_CLIENT_ID input must be provided."
        exit 1

    - name: Login to Azure - Prod Subscription
      if: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL != '' }}
      uses: Azure/login@e15b166166a8746d1a47596803bd8c1b595455cf # v1.6.0
      with:
        creds: ${{ inputs.AZURE_KV_CI_SERVICE_PRINCIPAL }}
    - name: Azure Login
      id: azure-login
      if: ${{ inputs.AZURE_CLIENT_ID != '' }}
      uses: bitwarden/gh-actions/azure-login@main
      with:
        subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        client_id: ${{ secrets.AZURE_CLIENT_ID }}

    - name: Retrieve Slack secrets
      id: retrieve-slack-secrets
      uses: bitwarden/gh-actions/get-keyvault-secrets@main
      with:
        keyvault: bitwarden-ci
        secrets: "slack-bot-token"

    - name: Azure Logout
      uses: bitwarden/gh-actions/azure-logout@main

    - name: Slack message setup
      id: setup
      shell: bash
      run: |
        function slack_message_fn () {
          local version="${{ inputs.version }}"
          local project="${{ inputs.project }}"
          SLACK_MESSAGE=":meow_attention: Upcoming release \`$version\` for \`$project\`."
        }

        slack_message_fn

        echo "slack_message<<EOF" >> $GITHUB_OUTPUT
        echo "$SLACK_MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Post message to a Slack channel
      id: slack-message
      uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
      with:
        channel-id: ${{ inputs.slack-channel }}
        slack-message: ${{ steps.setup.outputs.slack_message }}
      env:
        SLACK_BOT_TOKEN: ${{ steps.retrieve-slack-secrets.outputs.slack-bot-token }}
