name: 'Generate Container Image Tag'
description: 'Generates a standardized, sanitized container image tag for Docker images'
author: 'Bitwarden'
branding:
  icon: tag
  color: blue

inputs:
  ref:
    description: 'Branch or tag reference (use: github.head_ref || github.ref)'
    required: true

outputs:
  tag:
    description: 'The generated container image tag'
    value: ${{ steps.generate-tag.outputs.tag }}

runs:
  using: 'composite'
  steps:
    - name: Generate container image tag
      id: generate-tag
      shell: bash
      env:
        REF_INPUT: ${{ inputs.ref }}
      run: |
        # Extract branch/tag name from ref if it starts with refs/
        if [[ "${REF_INPUT}" == refs/* ]]; then
          BRANCH_NAME=$(echo "${REF_INPUT}" | sed 's|^refs/heads/||; s|^refs/tags/||')
        else
          # Already a plain branch name (from github.head_ref)
          BRANCH_NAME="${REF_INPUT}"
        fi

        # Sanitize the tag
        IMAGE_TAG=$(echo "${BRANCH_NAME}" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9._-]+/-/g; s/-+/-/g; s/^-+|-+$//g' | cut -c1-128 | sed -E 's/[.-]$//')

        # Transform 'main' branch to 'dev' tag
        if [[ "${IMAGE_TAG}" == "main" ]]; then
          IMAGE_TAG=dev
        fi

        # Validate tag is not empty
        if [[ -z "${IMAGE_TAG}" ]]; then
          echo "ERROR: Generated IMAGE_TAG is empty from input: ${REF_INPUT}"
          exit 1
        fi

        echo "tag=${IMAGE_TAG}" >> "$GITHUB_OUTPUT"
        echo "Generated container image tag: ${IMAGE_TAG}"
