# Workflow templates are based on starter workflows provided by github at 
# https://github.com/actions/starter-workflows/tree/main and customized to 
# represent common practices used on Bitwarden repositories.

name: CI

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request: # When a pull request event occurs

permissions: # Sets permissions of the GITHUB_TOKEN
  checks: write # Permits an action to create a check run
  contents: read # For actions to fetch code and list commits
  id-token: write # Required to fetch an OpenID Connect (OIDC) token
  pull-requests: write # Permits an action to add a label to a pull request

jobs:
  version:
    name: Calculate version
    uses: ./.github/workflows/_version.yml # Path to an existing github action

  test:
    name: Run test
    uses: ./.github/workflows/_test.yml
    with: # Parameters specific to this action that need to be defined in order for the step to be completed
      project-name: Billing.Test
      project-path: ./test/Billing.Test

  build:
    name: Run build
    needs:  # This job will not run until test and version jobs are complete
      - test
      - version
    uses: ./.github/workflows/_build.yml
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}

  build-push-docker:
    name: Build Docker image
    needs:
      - test
      - version
      - build
    uses: ./.github/workflows/_docker.yml
    with:
      project-name: Billing
      project-path: ./src/Billing
      version: ${{ needs.version.outputs.version }}
      image-name: billing-relay
      push-docker-image: false
