---
# Example workflow that runs on pull_request and can also be called from pull_request_target
# This workflow skips execution on external forks since it won't have access to secrets when invoked via pull_request
#
# Key patterns:
# 1. Triggered by pull_request (for internal PRs)
# 2. Can be called via workflow_call (from pull_request_target workflow for external PRs)
# 3. Skips execution on forks using condition when triggered with pull_request
# 4. Explicit permissions at workflow level

name: Example Workflow

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main
    paths:
      - "example/**"
      - ".github/workflows/example-workflow.yml"
  workflow_call:
    inputs:
      custom_parameter:
        description: "Optional custom parameter from calling workflow"
        required: false
        type: string
        default: "default-value"

permissions:
  contents: read

jobs:
  check-trigger:
    name: Check trigger source
    runs-on: ubuntu-24.04
    # Only run this job if the event is workflow_call or the PR is from the same repository (not a fork)
    # This avoid running it twice: once for pull_request from fork and once from pull_request_target
    if: github.event_name == 'workflow_call' || github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Check PR source and event
        run: echo "This PR is from the same repository (Not a fork) or called via workflow_call."
  example-job:
    name: Run example job
    runs-on: ubuntu-24.04
    needs: check-trigger # Only run if intended, otherwise skip
    permissions:
      contents: read
      id-token: write # Required if you need to authenticate to external services
    steps:
      - name: Get secrets
        run: echo "Series of steps that would retrieve secrets"

      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run some code
        run: |
          echo "Running workflow on branch: ${{ github.head_ref }}"
          echo "Custom parameter: ${{ inputs.custom_parameter }}"
          echo "This step could build, test, or deploy your code"
