name: Automated cherry pick
run-name: Automated cherry pick - ${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      source_pr:
        description: 'Pull request to cherry pick from. (e.g., 456)'
        required: true
        type: string
      dest_branch:
        description: 'Destination branch to cherry pick to. (e.g., hotfix-rc)'
        required: true
        type: choice
        options:
        - rc
        - hotfix-rc
        - rc-2024-02

# It's also possible to provide `dest_branch` as a string
#      dest_branch:
#        description: 'Destination branch to cherry pick to. (e.g., hotfix-rc)'
#        required: true
#        type: string

# Optionally provide an extended regex expression (ERE) pattern that `dest_branch` must match. Leave empty to disable.
env:
  #DEST_BRANCH_ALLOWED: '^20[2-9][0-9]\.[0-9][0-9]\-rc[0-9]$' # matches format `2025.01-rc2`
  _DEST_BRANCH_ALLOWED: ''
      

permissions: {}

jobs:
  cherry-pick:
    name: Cherry Pick
    uses: bitwarden/gh-actions/.github/workflows/_cherry-pick.yml@main
    with:
      source_pr: ${{ inputs.source_pr }}
      dest_branch: ${{ inputs.dest_branch }}
      dest_branch_allowed: ${{ env._DEST_BRANCH_ALLOWED }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
