name: Automated cherry pick
run-name: Automated cherry pick - ${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      source_pr:
        description: 'Pull request to cherry pick from'
        required: true
        type: string
      dest_branch:
        description: 'Destination branch to cherry pick to'
        required: true
        type: string

        ## alternative type for allow-list ##
        # type: choice
        # options:
        #  - rc
        #  - rc-2024-01
        #  - rc-2024-02

permissions: {}

jobs:
  cherry-pick:
    name: Cherry Pick
    uses: bitwarden/gh-actions/.github/workflows/_cherry-pick.yml@main
    with:
      source_pr: ${{ inputs.source_pr }}
      dest_branch: ${{ inputs.dest_branch }}
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
