name: Scan with Checkmarx

on:
  workflow_call:
    inputs:
      incremental:
        description: "Perform incremental scan"
        type: boolean
        default: ${{ contains(github.event_name, 'pull_request') }}
      upload-sarif:
        description: "Upload SARIF output to GitHub"
        type: boolean
        default: true
    secrets:
      AZURE_SUBSCRIPTION_ID:
        required: false
      AZURE_TENANT_ID:
        required: false
      AZURE_CLIENT_ID:
        required: false

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-checkmarx-${{ github.event.pull_request.number || github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  sast:
    name: SAST scan
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkmarx scanning disabled
        run: echo "Checkmarx scanning has been disabled."
