---
name: Get PR ID

on:
  workflow_call:
    inputs:
      commit-sha:
        type: string
        required: true
    outputs:
      id:
        description: "ID of PR that was associated to the merge to main that triggered the job"
        value: ${{ jobs.pr.outputs.id }}

jobs:
  pr:
    name: Get PR ID
    runs-on: ubuntu-22.04
    outputs:
      id: ${{ steps.pr.outputs.id }}
    steps:
      - name: Get PR ID
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          commit_message=$(
            curl -s -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/commits/${{ inputs.commit-sha }} | \
            jq -r ".commit.message"
          )
          ID=$(echo "$commit_message" | head -1 | grep -o "(#.*)" | grep -o "[0-9]*")
          echo "id=$ID" >> $GITHUB_OUTPUT

