name: Scan with Sonar

on:
  workflow_call: 

    inputs:
      sonar-config:
        description: "Configuration for Sonar"
        type: string
        default: "default"
      sonar-test-inclusions:
        type: string
        default: ""
      sonar-exclusions:
        type: string
        default: ""
      sonar-java-version:
        type: number
        default: 17
      sonar-java-distribution:
        type: string
        default: temurin
    secrets:
      SONAR_TOKEN:
        required: true

permissions: {}

jobs:

  quality:
    name: Quality scan
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Scan with Sonar
        if: inputs.sonar-config == 'default'
        uses: sonarsource/sonarqube-scan-action@2500896589ef8f7247069a56136f8dc177c27ccf # v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ github.repository_owner }}
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} 
            -Dsonar.test.inclusions=${{ inputs.sonar-test-inclusions }}
            -Dsonar.exclusions=${{ inputs.sonar-exclusions }}

      - name: Set up Java
        if: inputs.sonar-config == 'maven' || inputs.sonar-config == 'dotnet'
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: ${{ inputs.sonar-java-version }}
          distribution: ${{ inputs.sonar-java-distribution }}

      - name: Set up .NET
        if: inputs.sonar-config == 'dotnet'
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1

      - name: Install Sonar scanner
        if: inputs.sonar-config == 'dotnet'
        run: dotnet tool install dotnet-sonarscanner -g

      - name: Scan with Sonar
        if: inputs.sonar-config == 'dotnet'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin /k:"${{ github.repository_owner }}_${{ github.event.repository.name }}" \
          /d:sonar.test.inclusions=${{ inputs.sonar-test-inclusions }} \
          /d:sonar.exclusions=${{ inputs.sonar-exclusions }} \
          /o:"${{ github.repository_owner }}" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
          /d:sonar.host.url="https://sonarcloud.io" ${{ contains(github.event_name, 'pull_request') && format('/d:sonar.pullrequest.key={0}', github.event.pull_request.number) || '' }}
          dotnet build
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Scan with Sonar
        if: inputs.sonar-config == 'maven'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install -Dgpg.skip=true sonar:sonar -Dsonar.test.inclusions=${{ inputs.sonar-test-inclusions }} -Dsonar.exclusions=${{ inputs.sonar-exclusions }} ${{ contains(github.event_name, 'pull_request') && format('-Dsonar.pullrequest.key={0}', github.event.pull_request.number) || '' }}
