name: Scan with Zizmor

on:
  workflow_call:
    inputs:
      advanced-security:
        description: "Use Github Advanced Security functionality"
        type: boolean
        default: true

permissions: {}

jobs:
  quality:
    name: Zizmor
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: Check out repo
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@5ca5fc7a4779c5263a3ffa0e1f693009994446d1 # v0.1.2
        with:
          advanced-security: ${{ inputs.advanced-security }}
