name: CI-Lint

on:
  pull_request:
    paths:
      - "lint-workflow/**"
      - "lint-workflow-v2/**"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  ci-lint:
    name: CI workflow-linter (v1)
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.9.22"

      - name: Install dependencies
        working-directory: lint-workflow
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Test lint
        working-directory: lint-workflow
        run: pipenv run pytest tests
