name: Test Azure Login and Get Key Vault Action

on:
  pull_request:
    paths:
      - "azure-login/**"
      - "azure-logout/**"
      - "get-keyvault-secrets/**"
      - ".github/workflows/test-get-secrets.yml"

  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  test-repo-secrets:
    name: Test Get Secrets
    runs-on: ubuntu-22.04
    env:
      _TEST_SECRET_VALUE_1: Test Value 1
      _TEST_SECRET_VALUE_2: Test Value 2
    steps:
      - name: Azure Login
        id: azure-login
        uses: bitwarden/gh-actions/azure-login@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Verify Azure Login
        id: verify-login
        run: |
            az account show --query name --output tsv

      - name: Get KV Secrets
        id: get-kv-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: gh-gh-actions
          secrets: "test-secret-1,test-secret-2"

      - name: Azure Logout
        id: azure-logout
        uses: bitwarden/gh-actions/azure-logout@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality

      - name: Verify Logged Out
        id: verify-logout
        run: |
          az account show --query name --output tsv && (echo "Unexpectedly returned account name instead of being logged out" && exit 1) || echo "Successfully logged out of Azure"

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-kv-secrets.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE_1" ]]; then
            echo "test-secret-1 value is not as expected"
            exit 1
          fi
          if [[ "${{ steps.get-kv-secrets.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE_2" ]]; then
            echo "test-secret-2 value is not as expected"
            exit 1
          fi
          echo "Test secret values checks successful!"

  test-repo-env-secrets:
    name: Test Repo Environment Secrets
    runs-on: ubuntu-22.04
    environment: Testing
    env:
      _TEST_SECRET_VALUE_1: Test Environment Value
      _TEST_SECRET_VALUE_2: Test Value 2
    steps:
      - name: Azure Login
        id: azure-login
        uses: bitwarden/gh-actions/azure-login@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Verify Azure Login
        id: verify-login
        run: |
            az account show --query name --output tsv

      - name: Get KV Secrets
        id: get-kv-secrets-env
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: gh-gh-actions-testing
          secrets: "test-secret-1"

      # Env specific identities still need access to non env specific vaults
      - name: Get KV Secrets
        id: get-kv-secrets-repo
        uses: bitwarden/gh-actions/get-keyvault-secrets@main
        with:
          keyvault: gh-gh-actions
          secrets: "test-secret-2"

      - name: Azure Logout
        id: azure-logout
        uses: bitwarden/gh-actions/azure-logout@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality

      - name: Verify Logged Out
        id: verify-logout
        run: |
          az account show --query name --output tsv && (echo "Unexpectedly returned account name instead of being logged out" && exit 1) || echo "Successfully logged out of Azure"

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-kv-secrets-env.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE_1" ]]; then
            echo "test-secret-1 value is not as expected"
            exit 1
          fi
          if [[ "${{ steps.get-kv-secrets-repo.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE_2" ]]; then
            echo "test-secret-2 value is not as expected"
            exit 1
          fi
          echo "Test secret values checks successful!"
