name: Test Zizmor

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/test-zizmor.yml"
      - ".github/workflows/_zizmor.yml"
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  sast:
    name: Zizmor
    uses: ./.github/workflows/_zizmor.yml
    permissions:
      contents: read
      actions: read
      security-events: write
