name: Test Get Secrets Action

on:
  pull_request:
    paths:
      - "get-secrets"
      - ".github/workflows/test-get-secrets.yml"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read
  id-token: write

jobs:
  test-org-secret:
    name: Test Org Secret
    runs-on: ubuntu-22.04
    env:
      _TEST_SECRET_VALUE: test value
    steps:
      - name: Get Secrets
        id: get-secrets
        uses: bitwarden/gh-actions/get-secrets@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          lookup_repo_client_id: false
          secrets: test-secret

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-secrets.outputs.test-secret }}" != "$_TEST_SECRET_VALUE" ]]; then
            echo "Test secret value is not as expected"
            exit 1
          fi
          echo "Test secret value is as expected"

  test-repo-secrets:
    name: Test Repo Secrets
    runs-on: ubuntu-22.04
    env:
      _TEST_SECRET_VALUE: test value
    steps:
      - name: Get Secrets
        id: get-secrets
        uses: bitwarden/gh-actions/get-secrets@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          secrets: |
            test-secret-1
            test-secret-2

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-secrets.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE" ]]; then
            echo "Test secret 1 value is not as expected"
            exit 1
          fi
          if [[ "${{ steps.get-secrets.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE" ]]; then
            echo "Test secret 2 value is not as expected"
            exit 1
          fi
          echo "Test secret value is as expected"


  test-repo-env-secrets:
    name: Test Repo Secrets
    runs-on: ubuntu-22.04
    environment: Testing
    env:
      _TEST_SECRET_VALUE: test value - Testing
    steps:
      - name: Get Secrets
        id: get-secrets
        uses: bitwarden/gh-actions/get-secrets@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          keyvault_environment: Testing
          secrets: |
            test-secret-1
            test-secret-2

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-secrets.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE" ]]; then
            echo "Test secret 1 value is not as expected"
            exit 1
          fi
          if [[ "${{ steps.get-secrets.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE" ]]; then
            echo "Test secret 2 value is not as expected"
            exit 1
          fi
          echo "Test secret value is as expected"
