name: Test Sonar

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/test-sonar.yml"
      - ".github/workflows/_sonar.yml"
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  quality:
    name: Sonar
    uses: ./.github/workflows/_sonar.yml
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
