name: Test Lint Workflow Action

on:
  pull_request:
    paths:
      - "lint-workflow"
      - .github/workflows/test-lint-workflow.yml
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  test-lint-workflow:
    name: Test Lint Workflow
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout Branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get workflow list
        id: workflow-list
        run: |
          WORKFLOW_LIST=$(ls .github/workflows | xargs -I {} echo -n ".github/workflows/{} ")
          echo "workflow-list=$WORKFLOW_LIST" >> $GITHUB_OUTPUT

      - name: Lint Workflow
        uses: ./lint-workflow
        with:
          workflows: ${{ steps.workflow-list.outputs.workflow-list }}
