name: Test Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/test-review-code.yml"
      - ".github/workflows/review-code.yml"
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions: {}

jobs:
  review:
    name: Code Review
    uses: ./.github/workflows/review-code.yml
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
