name: Test Azure Login and Get Key Vault Action

on:
  pull_request:
    paths:
      - "azure-login/**"
      - "azure-logout/**"
      - "get-keyvault-secrets/**"
      - ".github/workflows/test-get-secrets.yml"

  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  customize_sub:
    runs-on: ubuntu-latest
    name: Customize OIDC sub
    permissions:
      actions: write
    steps:
      - name: Customize OIDC sub
        shell: bash
        run: |
          # curl -L \
          #   -H "Accept: application/vnd.github+json" \
          #   -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          #   -H "X-GitHub-Api-Version: 2022-11-28" \
          #   https://api.github.com/repos/${{ github.repository }}/actions/oidc/customization/sub

          curl -L \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/oidc/customization/sub \
            -d '{"use_default":false, "include_claim_keys":["repo"] }'

  test-repo-secrets:
    name: Test Get Secrets
    runs-on: ubuntu-22.04
    env:
      _TEST_SECRET_VALUE_1: Test Value 1
      _TEST_SECRET_VALUE_2: Test Value 2
    steps:
      - name: Azure Login
        id: azure-login
        uses: bitwarden/gh-actions/azure-login@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
        with:
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          client_id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Verify Azure Login
        id: verify-login
        run: |
            az account show --query name --output tsv

      - name: Get KV Secrets
        id: get-kv-secrets
        uses: bitwarden/gh-actions/get-keyvault-secrets@BRE-847-shared-secrets-action
        with:
          keyvault: gh-gh-actions
          secrets: "test-secret-1,test-secret-2"

      - name: Azure Logout
        id: azure-logout
        uses: bitwarden/gh-actions/azure-logout@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality

      - name: Verify Logged Out
        id: verify-logout
        run: |
          az account show --query name --output tsv && (echo "Unexpectedly returned account name instead of being logged out" && exit 1) || echo "Successfully logged out of Azure"

      - name: Verify test secret value
        run: |
          if [[ "${{ steps.get-kv-secrets.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE_1" ]]; then
            echo "test-secret-1 value is not as expected"
            exit 1
          fi
          if [[ "${{ steps.get-kv-secrets.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE_2" ]]; then
            echo "test-secret-2 value is not as expected"
            exit 1
          fi
          echo "Test secret values checks successful!"

      - name: Check environment
        run: |
          env | grep "test-secret"
          env | grep -q "test-secret"
          exit_code=$?
          if [ $exit_code -eq 0 ]; then
            echo "Found test secrets in environment"
            exit 1
          elif [ $exit_code -eq 1 ]; then
            echo "Correctly found no secrets found in environment"
          else
            exit $exit_code

  # test-repo-env-secrets:
  #   name: Test Repo Environment Secrets
  #   runs-on: ubuntu-22.04
  #   environment: Testing
  #   env:
  #     _TEST_SECRET_VALUE_1: Test Environment Value
  #     _TEST_SECRET_VALUE_2: Test Value 2
  #   steps:
  #     - name: Azure Login
  #       id: azure-login
  #       uses: bitwarden/gh-actions/azure-login@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality
  #       with:
  #         subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         tenant_id: ${{ secrets.AZURE_TENANT_ID }}
  #         client_id: ${{ secrets.AZURE_CLIENT_ID }}

  #     - name: Verify Azure Login
  #       id: verify-login
  #       run: |
  #           az account show --query name --output tsv

  #     - name: Get KV Secrets
  #       id: get-kv-secrets-env
  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
  #       with:
  #         keyvault: gh-gh-actions-testing
  #         secrets: "test-secret-1"

  #     # Env specific identities still need access to non env specific vaults
  #     - name: Get KV Secrets
  #       id: get-kv-secrets-repo
  #       uses: bitwarden/gh-actions/get-keyvault-secrets@main
  #       with:
  #         keyvault: gh-gh-actions
  #         secrets: "test-secret-2"

  #     - name: Azure Logout
  #       id: azure-logout
  #       uses: bitwarden/gh-actions/azure-logout@BRE-847-shared-secrets-action # TODO: Update to main after validating functionality

  #     - name: Verify Logged Out
  #       id: verify-logout
  #       run: |
  #         az account show --query name --output tsv && (echo "Unexpectedly returned account name instead of being logged out" && exit 1) || echo "Successfully logged out of Azure"

  #     - name: Verify test secret value
  #       run: |
  #         if [[ "${{ steps.get-kv-secrets-env.outputs.test-secret-1 }}" != "$_TEST_SECRET_VALUE_1" ]]; then
  #           echo "test-secret-1 value is not as expected"
  #           exit 1
  #         fi
  #         if [[ "${{ steps.get-kv-secrets-repo.outputs.test-secret-2 }}" != "$_TEST_SECRET_VALUE_2" ]]; then
  #           echo "test-secret-2 value is not as expected"
  #           exit 1
  #         fi
  #         echo "Test secret values checks successful!"
