name: Test Sonar

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - ".github/workflows/test-sonar.yml"
      - ".github/workflows/_sonar.yml"
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      sonar-config:
        description: "Configuration for Sonar"
        type: string
        default: "default"
      sonar-test-inclusions:
        description: "Glob pattern(s) for test files to include in Sonar analysis"
        type: string
      sonar-exclusions:
        description: "Glob pattern(s) for files to exclude from Sonar analysis"
        type: string

permissions: {}

jobs:
  quality:
    name: Sonar
    uses: ./.github/workflows/_sonar.yml
    secrets:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      sonar-config: ${{ github.event.inputs.sonar-config }}
      sonar-test-inclusions: ${{ github.event.inputs.sonar-test-inclusions }}
      sonar-exclusions: ${{ github.event.inputs.sonar-exclusions }}
