name: Test report-deployment-status-to-slack
on:
  pull_request:
    paths:
      - "report-deployment-status-to-slack/**"
      - ".github/workflows/test-report-deployment-status-to-slack.yml"

env:
  TEST_REPORT_PROJECT: Server
  TEST_REPORT_COMMIT_SHA: "50f7fa03dbc0f18a641206ab1a92fb11a1131572" # Use a valid commit in Server (TEST_REPORT_PROJECT) to validate the links

jobs:
  test-report-start:
    name: Test Slack report
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: Start
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: EU-QA Cloud
          tag: test-workflow-start
          event: "start"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Success
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: US-QA Cloud
          tag: test-workflow-success
          event: "success"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Failure
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: US-QA Cloud
          tag: test-workflow-failure
          event: "failure"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: No Changes
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: EU-QA Cloud
          tag: test-workflow-failure
          event: "no-changes"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

  test-report-db-migration:
    name: Test Slack report with different DB migration scenerios
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          persist-credentials: false

      - name: With DB migration true on main
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: EU-QA Cloud
          tag: main
          event: "success"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          db_migration_detected: true
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: With DB migration false on main
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: US-QA Cloud
          tag: main
          event: "failure"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          db_migration_detected: false
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: With DB migration true on test branch
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: EU-QA Cloud
          tag: test-branch-failure
          event: "failure"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          db_migration_detected: false
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: With DB migration false on test branch
        uses: ./report-deployment-status-to-slack
        with:
          project: ${{ env.TEST_REPORT_PROJECT }}
          environment: US-QA Cloud
          tag: test-branch-success
          event: "success"
          commit_sha: ${{ env.TEST_REPORT_COMMIT_SHA }}
          db_migration_detected: true
          url: https://github.com/bitwarden/gh-actions/actions/runs/${{ github.run_id }}
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
